name: Build and release

on: [workflow_dispatch]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Update package version
      shell: pwsh
      run: |
        $commitCount = git rev-list --count $env:GITHUB_REF
        $packageVersion = (Select-Xml -Path ./src/Directory.Build.props -XPath '/Project/PropertyGroup/PackageVersion').Node.InnerXML
        "ASSEMBLY_VERSION={0}" -f ($packageVersion -replace '^(.*)\.\d+.*$', "`$1.$commitCount.0") >> $env:GITHUB_ENV
        "PACKAGE_VERSION={0}" -f ($packageVersion -replace '^(.*)\.\d+.*$', "`$1.$commitCount") >> $env:GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore ./src/Hst.Amiga.sln
      
    - name: Build
      run: dotnet build ./src/Hst.Amiga.sln --configuration Release -p:Version=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} -p:FileVersion=${{ env.ASSEMBLY_VERSION }}
      
    - name: Test
      run: dotnet test ./src/Hst.Amiga.sln --configuration Release --no-build --verbosity normal --filter Category!=PFS3
      
    - name: Pack
      run: dotnet pack ./src/Hst.Amiga.sln --configuration Release -p:Version=${{ env.PACKAGE_VERSION }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:ProjectUrl=https://github.com/${{ github.repository }} -p:RepositoryUrl=https://github.com/${{ github.repository }}
      
    - name: Push
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
        dotnet nuget push **/bin/Release/*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push **/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_ORG_API_KEY }}